/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ColorBoard } from "./ColorBoard";
export * as factories from "./factories";
export { ColorBoard__factory } from "./factories/ColorBoard__factory";
